"""
Accessibility progress report PDF.

Aggregates `accessibility_usage_logs` for a student over a period and
prints a single-page A4 summary: which features they used, how often,
and what they changed. Companion to `progress_report_service.py` —
that one covers study hours and quiz averages, this one is about how
the student is using the accessibility platform itself.

Designed so a guardian can quickly answer "is the accessibility setup
actually working for them this week?"
"""

from __future__ import annotations

import io
from collections import Counter
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from services.certificate_service import _register_unicode_font


_CATEGORY_LABELS = {
    "visual": "Visual",
    "hearing": "Hearing",
    "motor": "Motor",
    "cognitive": "Cognitive",
    "speech": "Speech",
    "language": "Language",
}


def generate_accessibility_report_pdf(
    *,
    student_name: str,
    period_label: str,
    usage_rows: Iterable[Dict[str, Any]],
    generated_at: Optional[datetime] = None,
) -> bytes:
    """Render a single-page accessibility usage report PDF.

    `usage_rows` is an iterable of `accessibility_usage_logs` dicts with
    `feature_name` / `feature_category` / `action` / `created_at`.
    """
    _register_unicode_font()
    from services.certificate_service import _FONT_NAME as font, _FONT_NAME_BOLD as font_bold

    generated_at = generated_at or datetime.utcnow()
    rows = list(usage_rows)

    feature_counts: Counter = Counter()
    category_counts: Counter = Counter()
    action_counts: Counter = Counter()
    for r in rows:
        if r.get("feature_name"):
            feature_counts[r["feature_name"]] += 1
        if r.get("feature_category"):
            category_counts[r["feature_category"]] += 1
        if r.get("action"):
            action_counts[r["action"]] += 1

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    margin = 18 * mm
    y = height - margin

    c.setFont(font_bold, 20)
    c.drawString(margin, y, "Accessibility Progress Report")
    y -= 9 * mm

    c.setFont(font, 11)
    c.drawString(margin, y, f"Student: {student_name}")
    y -= 5 * mm
    c.drawString(margin, y, f"Period: {period_label}")
    y -= 5 * mm
    c.drawString(margin, y, f"Generated: {generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    y -= 9 * mm

    c.setFont(font_bold, 13)
    c.drawString(margin, y, "Summary")
    y -= 6 * mm
    c.setFont(font, 11)
    c.drawString(margin, y, f"Total accessibility interactions: {len(rows)}")
    y -= 5 * mm
    c.drawString(margin, y, f"Distinct features used: {len(feature_counts)}")
    y -= 9 * mm

    c.setFont(font_bold, 13)
    c.drawString(margin, y, "Most-used features")
    y -= 6 * mm
    c.setFont(font, 10)
    if feature_counts:
        for name, count in feature_counts.most_common(10):
            c.drawString(margin, y, f"• {name}")
            c.drawRightString(width - margin, y, f"{count}")
            y -= 5 * mm
            if y < margin + 30 * mm:
                break
    else:
        c.drawString(margin, y, "No accessibility activity recorded in this period.")
        y -= 5 * mm
    y -= 4 * mm

    c.setFont(font_bold, 13)
    c.drawString(margin, y, "By category")
    y -= 6 * mm
    c.setFont(font, 10)
    if category_counts:
        for cat, count in category_counts.most_common():
            label = _CATEGORY_LABELS.get(cat, cat)
            c.drawString(margin, y, f"• {label}")
            c.drawRightString(width - margin, y, f"{count}")
            y -= 5 * mm
            if y < margin + 18 * mm:
                break
    else:
        c.drawString(margin, y, "—")
        y -= 5 * mm

    c.setFont(font, 8)
    c.drawString(
        margin,
        margin,
        "Generated by SkillHub — keep this report for your records.",
    )

    c.showPage()
    c.save()
    buf.seek(0)
    return buf.getvalue()
