-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accessibility_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  disability_profile_id uuid,
  font_family character varying DEFAULT 'system'::character varying,
  font_size integer DEFAULT 100 CHECK (font_size >= 50 AND font_size <= 300),
  font_weight character varying DEFAULT 'normal'::character varying,
  letter_spacing numeric DEFAULT 0,
  word_spacing numeric DEFAULT 0,
  line_height numeric DEFAULT 1.5,
  color_scheme character varying DEFAULT 'default'::character varying,
  background_color character varying DEFAULT '#ffffff'::character varying,
  text_color character varying DEFAULT '#1a1a1a'::character varying,
  link_color character varying DEFAULT '#0066cc'::character varying,
  highlight_color character varying DEFAULT '#ffff00'::character varying,
  color_blind_mode character varying DEFAULT 'none'::character varying,
  color_blind_strength integer DEFAULT 100 CHECK (color_blind_strength >= 0 AND color_blind_strength <= 100),
  high_contrast boolean DEFAULT false,
  contrast_level integer DEFAULT 100 CHECK (contrast_level >= 50 AND contrast_level <= 200),
  brightness_level integer DEFAULT 100 CHECK (brightness_level >= 50 AND brightness_level <= 150),
  invert_colors boolean DEFAULT false,
  reduced_motion boolean DEFAULT false,
  disable_animations boolean DEFAULT false,
  disable_auto_play boolean DEFAULT true,
  disable_parallax boolean DEFAULT false,
  simplified_ui boolean DEFAULT false,
  large_click_targets boolean DEFAULT false,
  sticky_navigation boolean DEFAULT true,
  breadcrumbs_enabled boolean DEFAULT true,
  reading_mode character varying DEFAULT 'standard'::character varying,
  reading_guide boolean DEFAULT false,
  reading_ruler boolean DEFAULT false,
  text_mask boolean DEFAULT false,
  focus_highlight boolean DEFAULT false,
  screen_reader_optimized boolean DEFAULT false,
  text_to_speech boolean DEFAULT false,
  tts_voice character varying DEFAULT 'default'::character varying,
  tts_speed numeric DEFAULT 1.0 CHECK (tts_speed >= 0.5 AND tts_speed <= 2.0),
  tts_pitch numeric DEFAULT 1.0 CHECK (tts_pitch >= 0.5 AND tts_pitch <= 2.0),
  audio_descriptions boolean DEFAULT true,
  auto_captions boolean DEFAULT true,
  sign_language_videos boolean DEFAULT false,
  simplified_language boolean DEFAULT false,
  visual_learning_mode boolean DEFAULT false,
  step_by_step_mode boolean DEFAULT false,
  focus_mode boolean DEFAULT false,
  break_reminders boolean DEFAULT false,
  break_interval_minutes integer DEFAULT 25,
  progress_indicators boolean DEFAULT true,
  chunked_content boolean DEFAULT false,
  cognitive_load_indicator boolean DEFAULT false,
  keyboard_navigation boolean DEFAULT false,
  voice_input boolean DEFAULT false,
  switch_access boolean DEFAULT false,
  touch_accommodations boolean DEFAULT false,
  extended_time_default boolean DEFAULT false,
  math_visualization boolean DEFAULT false,
  calculator_always_visible boolean DEFAULT false,
  number_line_helper boolean DEFAULT false,
  step_by_step_math boolean DEFAULT false,
  spell_check_enhanced boolean DEFAULT true,
  grammar_suggestions boolean DEFAULT true,
  word_prediction boolean DEFAULT false,
  speech_to_text boolean DEFAULT false,
  quiet_mode boolean DEFAULT false,
  notification_sounds boolean DEFAULT true,
  visual_notifications boolean DEFAULT true,
  haptic_feedback boolean DEFAULT false,
  active_preset character varying DEFAULT 'custom'::character varying,
  custom_presets jsonb DEFAULT '{}'::jsonb,
  last_modified timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  sync_across_devices boolean DEFAULT true,
  CONSTRAINT accessibility_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT accessibility_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT accessibility_preferences_disability_profile_id_fkey FOREIGN KEY (disability_profile_id) REFERENCES public.student_disability_profiles(id)
);
CREATE TABLE public.accessibility_presets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  disability_type character varying,
  is_system_preset boolean DEFAULT false,
  created_by uuid,
  settings jsonb NOT NULL,
  usage_count integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accessibility_presets_pkey PRIMARY KEY (id),
  CONSTRAINT accessibility_presets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.accessibility_progress_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  guardian_link_id uuid,
  report_period_start timestamp without time zone NOT NULL,
  report_period_end timestamp without time zone NOT NULL,
  courses_active integer DEFAULT 0,
  courses_completed integer DEFAULT 0,
  average_progress numeric DEFAULT 0,
  study_hours numeric DEFAULT 0,
  accessibility_features_used jsonb DEFAULT '{}'::jsonb,
  accommodations_utilized jsonb DEFAULT '{}'::jsonb,
  session_count integer DEFAULT 0,
  average_session_duration numeric DEFAULT 0,
  break_compliance numeric DEFAULT 0,
  teacher_notes jsonb DEFAULT '[]'::jsonb,
  report_content jsonb,
  report_url text,
  sent_at timestamp without time zone,
  viewed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accessibility_progress_reports_pkey PRIMARY KEY (id),
  CONSTRAINT accessibility_progress_reports_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT accessibility_progress_reports_guardian_link_id_fkey FOREIGN KEY (guardian_link_id) REFERENCES public.guardian_links(id)
);
CREATE TABLE public.accessibility_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  feature_name character varying NOT NULL,
  feature_category character varying,
  action character varying,
  old_value text,
  new_value text,
  context_page character varying,
  session_id character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accessibility_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT accessibility_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  content text NOT NULL,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['user'::character varying::text, 'assistant'::character varying::text])),
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying::text, 'query_result'::character varying::text, 'error'::character varying::text])),
  metadata text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.content_sensory_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_id uuid NOT NULL UNIQUE,
  course_id uuid NOT NULL,
  visual_complexity integer DEFAULT 3 CHECK (visual_complexity >= 1 AND visual_complexity <= 5),
  color_count integer,
  has_animations boolean DEFAULT false,
  animation_speed text,
  has_flashing boolean DEFAULT false,
  contrast_level text DEFAULT 'standard'::text,
  auditory_complexity integer DEFAULT 3 CHECK (auditory_complexity >= 1 AND auditory_complexity <= 5),
  has_background_music boolean DEFAULT false,
  has_sound_effects boolean DEFAULT false,
  audio_clarity integer DEFAULT 3 CHECK (audio_clarity >= 1 AND audio_clarity <= 5),
  has_overlapping_audio boolean DEFAULT false,
  text_density integer DEFAULT 3 CHECK (text_density >= 1 AND text_density <= 5),
  concept_complexity integer DEFAULT 3 CHECK (concept_complexity >= 1 AND concept_complexity <= 5),
  multitasking_required boolean DEFAULT false,
  requires_sequential_processing boolean DEFAULT true,
  requires_precise_clicking boolean DEFAULT false,
  requires_typing boolean DEFAULT false,
  requires_dragging boolean DEFAULT false,
  has_time_limits boolean DEFAULT false,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_sensory_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT content_sensory_profiles_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  participant_1 uuid NOT NULL,
  participant_2 uuid NOT NULL,
  last_message_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_participant_1_fkey FOREIGN KEY (participant_1) REFERENCES public.users(id),
  CONSTRAINT conversations_participant_2_fkey FOREIGN KEY (participant_2) REFERENCES public.users(id)
);
CREATE TABLE public.course_accessibility_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL UNIQUE,
  has_captions boolean DEFAULT false,
  has_transcripts boolean DEFAULT false,
  has_audio_description boolean DEFAULT false,
  has_sign_language boolean DEFAULT false,
  has_simplified_version boolean DEFAULT false,
  has_visual_version boolean DEFAULT false,
  reading_level character varying,
  available_formats ARRAY DEFAULT '{}'::text[],
  suitable_for ARRAY DEFAULT '{}'::text[],
  not_recommended_for ARRAY DEFAULT '{}'::text[],
  allows_extended_time boolean DEFAULT true,
  flexible_deadlines boolean DEFAULT false,
  self_paced boolean DEFAULT false,
  break_friendly boolean DEFAULT true,
  cognitive_load_level character varying DEFAULT 'medium'::character varying,
  requires_fine_motor boolean DEFAULT false,
  requires_audio boolean DEFAULT false,
  requires_video boolean DEFAULT false,
  accommodation_notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT course_accessibility_info_pkey PRIMARY KEY (id),
  CONSTRAINT course_accessibility_info_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.course_accessibility_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  disability_type USER-DEFINED NOT NULL,
  compatibility_level integer DEFAULT 3 CHECK (compatibility_level >= 1 AND compatibility_level <= 5),
  has_captions boolean DEFAULT false,
  has_transcripts boolean DEFAULT false,
  has_audio_description boolean DEFAULT false,
  has_sign_language boolean DEFAULT false,
  has_simplified_version boolean DEFAULT false,
  has_extended_time boolean DEFAULT false,
  has_flashing_content boolean DEFAULT false,
  has_audio_required boolean DEFAULT false,
  has_video_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sensory_load USER-DEFINED DEFAULT 'medium'::sensory_load_level,
  primary_interaction_type USER-DEFINED DEFAULT 'mixed'::interaction_type,
  requires_sustained_attention boolean DEFAULT false,
  allows_self_pacing boolean DEFAULT true,
  estimated_cognitive_load integer DEFAULT 3 CHECK (estimated_cognitive_load >= 1 AND estimated_cognitive_load <= 5),
  recommended_break_frequency integer,
  average_session_length integer,
  CONSTRAINT course_accessibility_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.course_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  content_type USER-DEFINED NOT NULL,
  content_url text,
  duration character varying,
  file_size character varying,
  access_level USER-DEFINED DEFAULT 'free'::access_level,
  order_index integer,
  is_downloadable boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT course_content_pkey PRIMARY KEY (id),
  CONSTRAINT course_content_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.course_enrollments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::enrollment_status,
  progress_percentage integer DEFAULT 0,
  enrolled_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp without time zone,
  last_accessed timestamp without time zone,
  payment_status character varying DEFAULT 'pending'::character varying,
  payment_amount numeric,
  CONSTRAINT course_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT course_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_enrollments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  teacher_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  subject_id uuid,
  level character varying,
  duration_weeks integer,
  price numeric,
  original_price numeric,
  max_students integer,
  status USER-DEFINED DEFAULT 'draft'::course_status,
  thumbnail_url text,
  is_featured boolean DEFAULT false,
  tags ARRAY,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id),
  CONSTRAINT courses_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.dashboard_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  metric_type character varying NOT NULL,
  metric_value integer DEFAULT 0,
  date_recorded date DEFAULT CURRENT_DATE,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dashboard_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.disability_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  is_complete boolean DEFAULT false,
  assisted_by text,
  assistant_relationship text,
  assessment_version integer DEFAULT 1,
  responses jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disability_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT disability_assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.event_registrations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  attendance_status character varying DEFAULT 'registered'::character varying,
  payment_status character varying DEFAULT 'pending'::character varying,
  payment_amount numeric,
  CONSTRAINT event_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT event_registrations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organizer_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  category USER-DEFINED NOT NULL,
  start_date timestamp without time zone NOT NULL,
  end_date timestamp without time zone NOT NULL,
  location character varying,
  is_online boolean DEFAULT true,
  price numeric DEFAULT 0,
  original_price numeric,
  max_attendees integer,
  current_attendees integer DEFAULT 0,
  image_url text,
  tags ARRAY,
  level character varying,
  languages ARRAY,
  has_certificate boolean DEFAULT false,
  sponsor character varying,
  is_featured boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.users(id)
);
CREATE TABLE public.examination_results (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  exam_id uuid NOT NULL,
  student_id uuid NOT NULL,
  marks_obtained integer,
  grade character varying,
  percentage numeric,
  is_passed boolean,
  remarks text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT examination_results_pkey PRIMARY KEY (id),
  CONSTRAINT examination_results_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES public.examinations(id),
  CONSTRAINT examination_results_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id)
);
CREATE TABLE public.examinations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  exam_date timestamp without time zone NOT NULL,
  duration_minutes integer,
  total_marks integer,
  passing_marks integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT examinations_pkey PRIMARY KEY (id),
  CONSTRAINT examinations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT examinations_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);
CREATE TABLE public.forum_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  author_id uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  category USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'active'::post_status,
  tags ARRAY,
  upvotes integer DEFAULT 0,
  downvotes integer DEFAULT 0,
  views integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  is_pinned boolean DEFAULT false,
  is_solved boolean DEFAULT false,
  has_image boolean DEFAULT false,
  has_poll boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forum_posts_pkey PRIMARY KEY (id),
  CONSTRAINT forum_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.forum_replies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL,
  upvotes integer DEFAULT 0,
  downvotes integer DEFAULT 0,
  is_solution boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forum_replies_pkey PRIMARY KEY (id),
  CONSTRAINT forum_replies_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.forum_posts(id),
  CONSTRAINT forum_replies_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.forum_votes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  post_id uuid,
  reply_id uuid,
  vote_type character varying NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT forum_votes_pkey PRIMARY KEY (id),
  CONSTRAINT forum_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT forum_votes_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.forum_posts(id),
  CONSTRAINT forum_votes_reply_id_fkey FOREIGN KEY (reply_id) REFERENCES public.forum_replies(id)
);
CREATE TABLE public.group_memberships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying,
  joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  CONSTRAINT group_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT group_memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.learning_groups(id),
  CONSTRAINT group_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.group_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  group_id uuid NOT NULL,
  author_id uuid NOT NULL,
  content text NOT NULL,
  attachments ARRAY,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_posts_pkey PRIMARY KEY (id),
  CONSTRAINT group_posts_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.learning_groups(id),
  CONSTRAINT group_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id)
);
CREATE TABLE public.guardian_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  guardian_id uuid,
  guardian_email character varying NOT NULL,
  guardian_name character varying,
  guardian_phone character varying,
  relationship character varying,
  can_view_progress boolean DEFAULT true,
  can_view_grades boolean DEFAULT true,
  can_view_accessibility boolean DEFAULT true,
  can_communicate_teachers boolean DEFAULT true,
  can_modify_accessibility boolean DEFAULT false,
  receives_reports boolean DEFAULT true,
  report_frequency character varying DEFAULT 'weekly'::character varying,
  is_verified boolean DEFAULT false,
  verification_code character varying,
  verified_at timestamp without time zone,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT guardian_links_pkey PRIMARY KEY (id),
  CONSTRAINT guardian_links_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT guardian_links_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES public.users(id)
);
CREATE TABLE public.inferred_disabilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  assessment_id uuid,
  disability_type USER-DEFINED NOT NULL,
  confidence_score numeric NOT NULL CHECK (confidence_score >= 0::numeric AND confidence_score <= 100::numeric),
  severity USER-DEFINED NOT NULL,
  color_vision_subtype USER-DEFINED,
  user_confirmed boolean,
  user_confirmed_at timestamp with time zone,
  professionally_diagnosed boolean DEFAULT false,
  diagnosis_date date,
  diagnosing_professional text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inferred_disabilities_pkey PRIMARY KEY (id),
  CONSTRAINT inferred_disabilities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT inferred_disabilities_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.disability_assessments(id)
);
CREATE TABLE public.learning_groups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  subject_id uuid,
  group_type USER-DEFINED NOT NULL,
  level character varying,
  admin_id uuid NOT NULL,
  max_members integer,
  current_members integer DEFAULT 1,
  language character varying,
  meeting_schedule character varying,
  location character varying,
  activity_level character varying,
  image_url text,
  tags ARRAY,
  is_private boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'pending_approval'::group_status,
  upcoming_session text,
  achievements ARRAY,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  last_activity timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT learning_groups_pkey PRIMARY KEY (id),
  CONSTRAINT learning_groups_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.users(id),
  CONSTRAINT learning_groups_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.live_meeting_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  meeting_type USER-DEFINED NOT NULL,
  host_id uuid NOT NULL,
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone NOT NULL,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  status USER-DEFINED DEFAULT 'scheduled'::meeting_status,
  room_id text NOT NULL UNIQUE,
  max_participants integer DEFAULT 50,
  current_participant_count integer DEFAULT 0,
  video_enabled boolean DEFAULT true,
  audio_enabled boolean DEFAULT true,
  screen_share_enabled boolean DEFAULT true,
  chat_enabled boolean DEFAULT true,
  recording_enabled boolean DEFAULT false,
  captions_enabled boolean DEFAULT false,
  recording_started_at timestamp with time zone,
  recording_url text,
  recording_size_bytes bigint,
  accessibility_mode_enabled boolean DEFAULT false,
  low_distraction_mode boolean DEFAULT false,
  high_contrast_mode boolean DEFAULT false,
  large_controls boolean DEFAULT false,
  course_id uuid,
  session_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT live_meeting_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT live_meeting_rooms_host_id_fkey FOREIGN KEY (host_id) REFERENCES auth.users(id)
);
CREATE TABLE public.live_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  teacher_id uuid NOT NULL,
  course_id uuid,
  title character varying NOT NULL,
  description text,
  session_type USER-DEFINED NOT NULL,
  session_mode USER-DEFINED DEFAULT 'online'::session_mode,
  scheduled_start timestamp without time zone NOT NULL,
  scheduled_end timestamp without time zone NOT NULL,
  actual_start timestamp without time zone,
  actual_end timestamp without time zone,
  status USER-DEFINED DEFAULT 'scheduled'::session_status,
  meeting_link text,
  location character varying,
  max_participants integer,
  current_participants integer DEFAULT 0,
  recording_enabled boolean DEFAULT true,
  recording_url text,
  recording_expires_at timestamp without time zone,
  is_recurring boolean DEFAULT false,
  recurrence_pattern text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT live_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT live_sessions_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id),
  CONSTRAINT live_sessions_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.meeting_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  total_participants integer DEFAULT 0,
  average_attendance_minutes numeric,
  peak_concurrent_users integer DEFAULT 0,
  total_messages integer DEFAULT 0,
  total_reactions integer DEFAULT 0,
  screen_shares_count integer DEFAULT 0,
  average_connection_quality numeric,
  disconnect_count integer DEFAULT 0,
  captions_used_count integer DEFAULT 0,
  keyboard_navigation_users integer DEFAULT 0,
  computed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_analytics_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id)
);
CREATE TABLE public.meeting_captions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  speaker_id uuid,
  speaker_name text,
  text text NOT NULL,
  timestamp_offset_seconds numeric NOT NULL,
  duration_seconds numeric,
  confidence numeric,
  language text DEFAULT 'en'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_captions_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_captions_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id),
  CONSTRAINT meeting_captions_speaker_id_fkey FOREIGN KEY (speaker_id) REFERENCES auth.users(id)
);
CREATE TABLE public.meeting_chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  user_id uuid NOT NULL,
  message text NOT NULL,
  message_type text DEFAULT 'text'::text,
  is_private boolean DEFAULT false,
  recipient_id uuid,
  reactions jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_chat_messages_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id),
  CONSTRAINT meeting_chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT meeting_chat_messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.meeting_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED DEFAULT 'participant'::participant_role,
  joined_at timestamp with time zone,
  left_at timestamp with time zone,
  is_currently_in_meeting boolean DEFAULT false,
  video_enabled boolean DEFAULT true,
  audio_enabled boolean DEFAULT true,
  is_screen_sharing boolean DEFAULT false,
  connection_quality text,
  last_seen timestamp with time zone,
  needs_captions boolean DEFAULT false,
  prefers_large_video boolean DEFAULT false,
  prefers_low_distraction boolean DEFAULT false,
  keyboard_only_mode boolean DEFAULT false,
  total_time_minutes integer DEFAULT 0,
  attended boolean DEFAULT false,
  spoke_count integer DEFAULT 0,
  message_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_participants_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_participants_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id),
  CONSTRAINT meeting_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.meeting_recordings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  storage_path text NOT NULL,
  file_size_bytes bigint,
  duration_seconds integer,
  format text DEFAULT 'mp4'::text,
  processing_status text DEFAULT 'processing'::text,
  processing_started_at timestamp with time zone,
  processing_completed_at timestamp with time zone,
  has_captions boolean DEFAULT false,
  captions_file_path text,
  is_public boolean DEFAULT false,
  password_protected boolean DEFAULT false,
  expires_at timestamp with time zone,
  view_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_recordings_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_recordings_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  attachments ARRAY,
  is_read boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  data jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.oauth_account_linking_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider character varying NOT NULL,
  provider_user_id character varying NOT NULL,
  provider_email character varying NOT NULL,
  oauth_data jsonb NOT NULL,
  existing_user_id uuid,
  existing_user_email character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  verification_token character varying NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  expires_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP + '24:00:00'::interval),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT oauth_account_linking_requests_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_account_linking_requests_existing_user_id_fkey FOREIGN KEY (existing_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.oauth_security_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  provider character varying NOT NULL,
  provider_user_id character varying,
  event_type character varying NOT NULL,
  event_description text,
  ip_address inet,
  user_agent text,
  session_id character varying,
  token_audience character varying,
  token_issuer character varying,
  scopes_requested ARRAY,
  risk_score integer DEFAULT 0,
  risk_factors ARRAY,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT oauth_security_logs_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_security_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.partnerships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sponsor_id uuid NOT NULL,
  partner_name character varying NOT NULL,
  partner_type character varying,
  partnership_level character varying,
  start_date date,
  location character varying,
  description text,
  projects_count integer DEFAULT 0,
  students_impacted integer DEFAULT 0,
  schools_count integer DEFAULT 0,
  investment_amount numeric,
  roi_percentage numeric,
  contact_person character varying,
  contact_email character varying,
  contact_phone character varying,
  benefits ARRAY,
  objectives ARRAY,
  recent_activity text,
  next_meeting date,
  logo_url text,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT partnerships_pkey PRIMARY KEY (id),
  CONSTRAINT partnerships_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsor_profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  payment_type USER-DEFINED NOT NULL,
  reference_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'LKR'::character varying,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  payment_method character varying,
  transaction_id character varying,
  payment_gateway character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  processed_at timestamp without time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reporter_id uuid NOT NULL,
  reported_user_id uuid,
  reported_post_id uuid,
  reported_message_id uuid,
  category USER-DEFINED NOT NULL,
  description text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::report_status,
  admin_notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamp without time zone,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.users(id),
  CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.users(id),
  CONSTRAINT reports_reported_post_id_fkey FOREIGN KEY (reported_post_id) REFERENCES public.forum_posts(id),
  CONSTRAINT reports_reported_message_id_fkey FOREIGN KEY (reported_message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reviewer_id uuid NOT NULL,
  teacher_id uuid,
  course_id uuid,
  event_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  content text,
  is_verified boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id),
  CONSTRAINT reviews_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT reviews_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.session_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  student_id uuid NOT NULL,
  joined_at timestamp without time zone,
  left_at timestamp without time zone,
  attendance_duration_minutes integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT session_participants_pkey PRIMARY KEY (id),
  CONSTRAINT session_participants_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.live_sessions(id),
  CONSTRAINT session_participants_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id)
);
CREATE TABLE public.sponsor_campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sponsor_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  budget numeric NOT NULL,
  students_reached integer DEFAULT 0,
  completion_percentage integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'draft'::campaign_status,
  start_date date,
  end_date date,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sponsor_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT sponsor_campaigns_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsor_profiles(id)
);
CREATE TABLE public.sponsor_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  company_name character varying NOT NULL,
  industry character varying,
  website character varying,
  description text,
  logo_url text,
  contact_person character varying,
  contact_email character varying,
  contact_phone character varying,
  total_investment numeric DEFAULT 0,
  active_campaigns integer DEFAULT 0,
  students_reached integer DEFAULT 0,
  roi_percentage numeric DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sponsor_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT sponsor_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sponsorship_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  amount_requested numeric NOT NULL,
  students_impacted integer DEFAULT 0,
  status character varying DEFAULT 'pending'::character varying,
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  reviewed_at timestamp with time zone,
  reviewer_notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sponsorship_requests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_sponsorship_teacher FOREIGN KEY (teacher_id) REFERENCES public.users(id)
);
CREATE TABLE public.student_course_accommodations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  course_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  extended_time_percentage integer DEFAULT 0,
  flexible_deadlines boolean DEFAULT false,
  alternative_assignments boolean DEFAULT false,
  note_taking_assistance boolean DEFAULT false,
  recording_allowed boolean DEFAULT true,
  simplified_content boolean DEFAULT false,
  audio_version boolean DEFAULT false,
  large_print boolean DEFAULT false,
  oral_exams_allowed boolean DEFAULT false,
  calculator_allowed boolean DEFAULT true,
  formula_sheet_allowed boolean DEFAULT false,
  breaks_during_exams boolean DEFAULT true,
  separate_testing_room boolean DEFAULT false,
  custom_accommodations jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'pending'::character varying,
  approved_by uuid,
  approved_at timestamp without time zone,
  expires_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT student_course_accommodations_pkey PRIMARY KEY (id),
  CONSTRAINT student_course_accommodations_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT student_course_accommodations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT student_course_accommodations_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);
CREATE TABLE public.student_disability_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  has_disability boolean DEFAULT false,
  disability_types ARRAY DEFAULT '{}'::text[],
  primary_disability character varying,
  severity_levels jsonb DEFAULT '{}'::jsonb,
  professionally_diagnosed boolean DEFAULT false,
  diagnosis_date timestamp without time zone,
  iep_status boolean DEFAULT false,
  accommodation_letter boolean DEFAULT false,
  guardian_consent boolean DEFAULT false,
  guardian_email character varying,
  guardian_phone character varying,
  guardian_relationship character varying,
  additional_needs text,
  medical_notes text,
  share_with_teachers boolean DEFAULT true,
  share_with_sponsors boolean DEFAULT false,
  onboarding_completed boolean DEFAULT false,
  last_assessment_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT student_disability_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT student_disability_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.student_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  enrollment_id uuid NOT NULL,
  content_id uuid NOT NULL,
  progress_percentage integer DEFAULT 0,
  time_spent_minutes integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  last_accessed timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT student_progress_pkey PRIMARY KEY (id),
  CONSTRAINT student_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.course_enrollments(id),
  CONSTRAINT student_progress_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.course_content(id)
);
CREATE TABLE public.student_teacher_accessibility_sharing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  share_disability_types boolean DEFAULT true,
  share_severity boolean DEFAULT false,
  share_specific_needs boolean DEFAULT true,
  share_accommodation_notes boolean DEFAULT true,
  auto_approved boolean DEFAULT true,
  manually_revoked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT student_teacher_accessibility_sharing_pkey PRIMARY KEY (id),
  CONSTRAINT student_teacher_accessibility_sharing_student_id_fkey FOREIGN KEY (student_id) REFERENCES auth.users(id),
  CONSTRAINT student_teacher_accessibility_sharing_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subject_tags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  subject_id uuid,
  tag_name character varying NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT subject_tags_pkey PRIMARY KEY (id),
  CONSTRAINT subject_tags_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.subjects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  category character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT subjects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teacher_accessibility_training (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  training_name character varying NOT NULL,
  training_provider character varying,
  training_type character varying,
  disability_focus ARRAY DEFAULT '{}'::text[],
  completed_date timestamp without time zone,
  expiry_date timestamp without time zone,
  certificate_url text,
  hours_completed integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT teacher_accessibility_training_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_accessibility_training_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);
CREATE TABLE public.teacher_communication_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL UNIQUE,
  accepts_student_messages boolean DEFAULT true,
  accepts_parent_messages boolean DEFAULT true,
  accepts_sponsor_meetings boolean DEFAULT false,
  accepts_teacher_collaboration boolean DEFAULT true,
  typical_response_time_hours integer DEFAULT 24,
  available_for_video_calls boolean DEFAULT true,
  available_for_voice_calls boolean DEFAULT true,
  available_for_text_chat boolean DEFAULT true,
  office_hours jsonb DEFAULT '[]'::jsonb,
  open_to_co_teaching boolean DEFAULT false,
  open_to_mentoring boolean DEFAULT true,
  preferred_communication_language ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teacher_communication_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_communication_preferences_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id)
);
CREATE TABLE public.teacher_disability_specializations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  disability_type USER-DEFINED NOT NULL,
  specialization_level USER-DEFINED DEFAULT 'basic'::specialization_level,
  certified boolean DEFAULT false,
  certification_name text,
  certification_date date,
  certification_expiry date,
  years_experience integer DEFAULT 0,
  students_taught integer DEFAULT 0,
  comfort_level integer DEFAULT 3 CHECK (comfort_level >= 1 AND comfort_level <= 5),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teacher_disability_specializations_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_disability_specializations_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id)
);
CREATE TABLE public.teacher_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying,
  experience_years integer,
  hourly_rate numeric,
  languages ARRAY,
  specializations ARRAY,
  achievements ARRAY,
  teaching_style text,
  is_verified boolean DEFAULT false,
  is_online_available boolean DEFAULT true,
  is_physical_available boolean DEFAULT true,
  response_time character varying,
  availability_status character varying DEFAULT 'Available'::character varying,
  total_students integer DEFAULT 0,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  collaboration_interests ARRAY,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT teacher_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.teacher_specializations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL UNIQUE,
  specializations ARRAY DEFAULT '{}'::text[],
  disability_experience ARRAY DEFAULT '{}'::text[],
  certifications jsonb DEFAULT '[]'::jsonb,
  training_completed jsonb DEFAULT '[]'::jsonb,
  years_special_education integer DEFAULT 0,
  teaching_methods ARRAY DEFAULT '{}'::text[],
  accommodation_strategies jsonb DEFAULT '{}'::jsonb,
  assistive_tech_proficiency ARRAY DEFAULT '{}'::text[],
  sign_language_proficiency character varying,
  braille_proficiency character varying,
  aac_experience boolean DEFAULT false,
  accepts_iep_students boolean DEFAULT true,
  max_special_needs_students integer DEFAULT 5,
  inclusion_rating numeric DEFAULT 0,
  inclusion_reviews_count integer DEFAULT 0,
  verified_specialist boolean DEFAULT false,
  verification_date timestamp without time zone,
  verified_by character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT teacher_specializations_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_specializations_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);
CREATE TABLE public.teacher_sponsor_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  sponsor_id uuid NOT NULL,
  connection_type text DEFAULT 'general'::text,
  status text DEFAULT 'pending'::text,
  total_meetings integer DEFAULT 0,
  last_meeting_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teacher_sponsor_connections_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_sponsor_connections_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id),
  CONSTRAINT teacher_sponsor_connections_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.teacher_subjects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  teacher_id uuid,
  subject_id uuid,
  proficiency_level character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT teacher_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT teacher_subjects_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id),
  CONSTRAINT teacher_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id)
);
CREATE TABLE public.transcripts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  student_id uuid NOT NULL,
  teacher_id uuid NOT NULL,
  course_id uuid NOT NULL,
  transcript_url text NOT NULL,
  uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_verified boolean DEFAULT false,
  CONSTRAINT transcripts_pkey PRIMARY KEY (id),
  CONSTRAINT transcripts_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id),
  CONSTRAINT transcripts_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id),
  CONSTRAINT transcripts_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.user_activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_type character varying NOT NULL,
  activity_description text,
  ip_address inet,
  user_agent text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_adaptation_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  is_auto_generated boolean DEFAULT true,
  based_on_assessment_id uuid,
  font_family text DEFAULT 'system-ui, -apple-system, sans-serif'::text,
  font_size integer DEFAULT 100 CHECK (font_size >= 50 AND font_size <= 300),
  line_height numeric DEFAULT 1.5,
  letter_spacing numeric DEFAULT 0,
  word_spacing numeric DEFAULT 0,
  text_color text DEFAULT '#1a1a1a'::text,
  background_color text DEFAULT '#ffffff'::text,
  high_contrast boolean DEFAULT false,
  color_filter USER-DEFINED DEFAULT 'none'::color_vision_type,
  reduced_animations boolean DEFAULT false,
  focus_mode boolean DEFAULT false,
  simplified_ui boolean DEFAULT false,
  chunk_content boolean DEFAULT false,
  break_reminders boolean DEFAULT false,
  break_interval_minutes integer DEFAULT 25,
  reading_guide boolean DEFAULT false,
  reading_ruler boolean DEFAULT false,
  text_to_speech boolean DEFAULT false,
  tts_rate numeric DEFAULT 1.0,
  tts_voice text,
  large_click_targets boolean DEFAULT false,
  keyboard_navigation boolean DEFAULT false,
  voice_input boolean DEFAULT false,
  extended_timeouts boolean DEFAULT false,
  timeout_multiplier numeric DEFAULT 1.5,
  visual_alerts boolean DEFAULT false,
  captions_enabled boolean DEFAULT false,
  sign_language_support boolean DEFAULT false,
  predictable_layout boolean DEFAULT false,
  reduced_sensory_input boolean DEFAULT false,
  clear_navigation_cues boolean DEFAULT false,
  last_auto_update timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_adaptation_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_adaptation_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_adaptation_profiles_based_on_assessment_id_fkey FOREIGN KEY (based_on_assessment_id) REFERENCES public.disability_assessments(id)
);
CREATE TABLE public.user_oauth_providers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL DEFAULT 'google'::character varying,
  provider_user_id character varying NOT NULL,
  provider_email character varying NOT NULL,
  access_token text,
  refresh_token text,
  id_token text,
  token_expires_at timestamp without time zone,
  provider_name character varying,
  provider_first_name character varying,
  provider_last_name character varying,
  provider_picture_url text,
  provider_locale character varying,
  provider_verified_email boolean DEFAULT false,
  is_primary_auth boolean DEFAULT false,
  account_linked_at timestamp without time zone,
  link_confirmation_required boolean DEFAULT false,
  last_used_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  ip_address inet,
  user_agent text,
  scopes_granted ARRAY,
  metadata jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_oauth_providers_pkey PRIMARY KEY (id),
  CONSTRAINT user_oauth_providers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  first_name character varying,
  last_name character varying,
  phone character varying,
  date_of_birth date,
  location character varying,
  bio text,
  avatar_url text,
  university character varying,
  student_id character varying,
  major character varying,
  year character varying,
  gpa numeric,
  reputation_score integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  address character varying,
  city character varying,
  country character varying,
  profile_picture_url text,
  website character varying,
  social_links jsonb,
  profile_picture_source character varying DEFAULT 'upload'::character varying,
  profile_picture_original_url text,
  profile_picture_last_sync timestamp without time zone,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  marketing_notifications boolean DEFAULT false,
  profile_visibility character varying DEFAULT 'public'::character varying,
  show_email boolean DEFAULT false,
  show_phone boolean DEFAULT false,
  show_location boolean DEFAULT true,
  theme character varying DEFAULT 'light'::character varying,
  language character varying DEFAULT 'en'::character varying,
  font_size character varying DEFAULT 'medium'::character varying,
  two_factor_auth boolean DEFAULT false,
  login_notifications boolean DEFAULT true,
  session_timeout integer DEFAULT 30,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  role USER-DEFINED NOT NULL,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.webrtc_signaling_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meeting_id uuid NOT NULL,
  from_user_id uuid NOT NULL,
  to_user_id uuid,
  message_type text NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT webrtc_signaling_messages_pkey PRIMARY KEY (id),
  CONSTRAINT webrtc_signaling_messages_meeting_id_fkey FOREIGN KEY (meeting_id) REFERENCES public.live_meeting_rooms(id),
  CONSTRAINT webrtc_signaling_messages_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES auth.users(id),
  CONSTRAINT webrtc_signaling_messages_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wishlists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  item_type USER-DEFINED NOT NULL,
  course_id uuid,
  event_id uuid,
  teacher_id uuid,
  added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT wishlists_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT wishlists_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT wishlists_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher_profiles(id)
);