defmodule SkillHubWeb.ProgressReportController do
  @moduledoc """
  Ported accessibility progress report (progress_reports.py). Aggregates
  `accessibility_usage_logs` over a week/month window and renders a PDF via
  headless Chrome.
  """
  use SkillHubWeb, :controller

  import SkillHubWeb.AuthHelpers
  alias SkillHub.SQL

  def download(conn, params) do
    with {:ok, _} <- require_role(conn, "student") do
      period = if params["period"] == "month", do: "month", else: "week"
      days = if period == "month", do: 30, else: 7
      user_id = uid(conn)

      total = SQL.scalar("select count(*)::int from public.accessibility_usage_logs where user_id = $1::uuid and created_at >= now() - ($2 || ' days')::interval", [user_id, to_string(days)], 0)

      features =
        SQL.maps(
          "select feature_name, count(*)::int c from public.accessibility_usage_logs where user_id = $1::uuid and created_at >= now() - ($2 || ' days')::interval group by feature_name order by c desc limit 12",
          [user_id, to_string(days)]
        )

      name =
        case SQL.one("select nullif(trim(coalesce(first_name,'') || ' ' || coalesce(last_name,'')), '') n from public.user_profiles where user_id = $1::uuid", [user_id]) do
          %{n: n} when is_binary(n) -> n
          _ -> "Student"
        end

      html = report_html(name, period, total, features)

      case SkillHub.PDF.render(html) do
        {:ok, pdf} ->
          conn
          |> put_resp_content_type("application/pdf")
          |> put_resp_header("content-disposition", ~s(attachment; filename="accessibility-report-#{period}.pdf"))
          |> put_resp_header("cache-control", "no-store")
          |> send_resp(200, pdf)

        {:error, :unavailable} ->
          conn |> put_status(503) |> json(%{detail: "PDF rendering unavailable (Chrome not found)."})

        {:error, _} ->
          conn |> put_status(500) |> json(%{detail: "Failed to render report."})
      end
    end
  end

  defp report_html(name, period, total, features) do
    label = if period == "month", do: "Past 30 days", else: "Past 7 days"
    max_c = features |> Enum.map(& &1.c) |> Enum.max(fn -> 1 end)

    bars =
      Enum.map_join(features, "", fn f ->
        pct = round(f.c / max(max_c, 1) * 100)
        """
        <div class="frow">
          <div class="fname">#{esc(humanize(f.feature_name))}</div>
          <div class="bar"><div class="fill" style="width:#{pct}%"></div></div>
          <div class="fcount">#{f.c}</div>
        </div>
        """
      end)

    features_block = if features == [], do: ~s(<p class="empty">No accessibility features were used in this period yet.</p>), else: bars

    """
    <!doctype html><html><head><meta charset="utf-8"><style>
      @page { size: A4; margin: 16mm; }
      body { font-family:"Segoe UI",Arial,sans-serif; color:#101828; margin:0; }
      .head { border-bottom:3px solid #7f56d9; padding-bottom:6mm; }
      .brand { font-size:20pt; font-weight:800; color:#7f56d9; }
      h1 { font-size:15pt; margin:8mm 0 1mm; color:#344054; }
      .sub { color:#98a2b3; font-size:10pt; }
      .cards { display:flex; gap:6mm; margin:8mm 0; }
      .card { flex:1; background:#f9f5ff; border:1px solid #e9d7fe; border-radius:8px; padding:5mm; text-align:center; }
      .card .n { font-size:26pt; font-weight:800; color:#7f56d9; }
      .card .l { font-size:9pt; color:#667085; text-transform:uppercase; letter-spacing:1px; }
      h2 { font-size:12pt; color:#344054; margin-top:8mm; }
      .frow { display:flex; align-items:center; gap:4mm; padding:2mm 0; font-size:10.5pt; }
      .fname { width:55mm; color:#344054; }
      .bar { flex:1; background:#f2f4f7; border-radius:4px; height:5mm; overflow:hidden; }
      .fill { height:100%; background:linear-gradient(90deg,#9e77ed,#7f56d9); }
      .fcount { width:14mm; text-align:right; color:#667085; font-weight:600; }
      .empty { color:#98a2b3; font-style:italic; }
      .foot { margin-top:14mm; text-align:center; color:#98a2b3; font-size:9pt; border-top:1px solid #eaecf0; padding-top:5mm; }
    </style></head><body>
      <div class="head"><div class="brand">SkillHub</div></div>
      <h1>Accessibility Usage Report</h1>
      <div class="sub">#{esc(name)} · #{label}</div>
      <div class="cards">
        <div class="card"><div class="n">#{total}</div><div class="l">Total interactions</div></div>
        <div class="card"><div class="n">#{length(features)}</div><div class="l">Features used</div></div>
      </div>
      <h2>Feature usage</h2>
      #{features_block}
      <div class="foot">Generated by SkillHub — inclusive education for every learner.</div>
    </body></html>
    """
  end

  defp humanize(nil), do: "Feature"
  defp humanize(s), do: s |> to_string() |> String.replace("_", " ") |> String.split() |> Enum.map_join(" ", &String.capitalize/1)

  defp esc(nil), do: ""
  defp esc(s), do: s |> to_string() |> String.replace("&", "&amp;") |> String.replace("<", "&lt;") |> String.replace(">", "&gt;")

  defp uid(conn), do: conn.assigns.current_user_id
end
