defmodule SkillHubWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :skillhub

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_skillhub_key",
    signing_salt: "xVQSkwZG",
    same_site: "Lax"
  ]

  # Realtime WebSocket for notifications (and future channels). The client
  # authenticates with `?token=<jwt>` at connect time (see UserSocket).
  socket "/socket", SkillHubWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :skillhub,
    gzip: not code_reloading?,
    only: SkillHubWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :skillhub
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # CORS for the Next.js frontend. Answers preflight (OPTIONS) and stamps the
  # allow-* headers on every response — including proxied ones. Placed before
  # the proxy so upstream CORS headers are stripped and never duplicated.
  plug CORSPlug,
    origin: &SkillHubWeb.cors_origins/0,
    credentials: true,
    headers: ["*"]

  # Strangler gateway: forwards any non-natively-ported route to Python using
  # the RAW body — so it must run before Plug.Parsers.
  plug SkillHubWeb.Plugs.StranglerProxy

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SkillHubWeb.Router
end
